project:
    type: website
    
website:
  title: "Austin Hoover"
  open-graph: true
  navbar:
    right:
      - text: "Home"
        href: ./index.qmd
      - text: "Research"
        href: ./research/index.qmd
      - text: "Papers"
        menu: 
          - text: "Journal"
            href: ./papers/index.qmd
          - text: "Conference"
            href: ./papers/conference.qmd
          - text: "Miscellaneous"
            href: ./papers/misc.qmd     
      - text: "Talks"
        href: ./talks/index.qmd
      - text: "News"
        href: ./news/index.qmd
  google-analytics: "G-NS0H6D6VKL"
format:
  html:
    theme: 
      light: [default, style/custom.scss] 
    fontsize: 14px  
    grid:
      body-width: 650px
    lightbox: true
    html-math-method: mathjax
    highlight-style: github    
    toc: false