project:
    type: website
    
website:
  title: "Austin Hoover"
  open-graph: true
  navbar:
    right:
      - text: "Home"
        href: ./index.qmd
      - text: "Research"
        href: ./research/index.qmd
      - text: "News"
        href: ./news/index.qmd
  google-analytics: "G-NS0H6D6VKL"
format:
  html:
    theme: 
      light: [default, style/custom.scss] 
    fontsize: 13px  
    grid:
      body-width: 700px
    lightbox: true
    html-math-method: mathjax
    highlight-style: github    
