project:
    type: website
    
website:
  title: "Austin Hoover"
  open-graph: true
  navbar:
    right:
      - text: "Home"
        href: ./index.qmd
      - text: "Research"
        href: ./research/index.qmd
      - text: "Publications"
        menu:
          - href: ./publications/index.qmd
            text: "Papers"
          - href: ./publications/presentations.qmd
            text: "Presentations"
          - href: ./publications/misc.qmd
            text: "Miscellaneous"
      - text: "News"
        href: ./news/index.qmd
  google-analytics: "G-NS0H6D6VKL"
format:
  html:
    theme: 
      - default
      - style/custom.scss
    fontsize: 13px
    grid:
      body-width: 625px
    lightbox: true
    html-math-method: mathjax
    highlight-style: github    
    css: style/style.css
